import React,{FormEvent,useEffect,useMemo,useState}from'react';
import toast from'react-hot-toast';
import{Modal}from'../../../components/ui/Modal';
import{useCreatePricingPreset,useUpdatePricingPreset}from'../hooks/usePricingPresets';
import{usePricingCalculation}from'../hooks/usePricingPreview';
import{pricingPresetFormSchema,PricingPresetFormValues}from'../schemas/pricing.schemas';
import{PricingPreset}from'../types/pricing.types';
import{pricingLabels}from'../utils/pricing-labels';
import{PricingPreviewCard}from'./PricingPreviewCard';

const formulaFields=['expensePercent','profitPercent','discountBufferPercent','installmentMarkupPercent','downPaymentPercent','defaultInstallmentMonths','calculationMode','roundingMode']as const;
const percentFields=['expensePercent','profitPercent','discountBufferPercent','installmentMarkupPercent','downPaymentPercent']as const;
const empty:PricingPresetFormValues={name:'',productType:'',expensePercent:'0',profitPercent:'0',discountBufferPercent:'0',installmentMarkupPercent:'0',downPaymentPercent:'0',defaultInstallmentMonths:'3',calculationMode:'COMPOUND',roundingMode:'NONE',notes:'',sampleCost:'100.00',reason:'',accountPassword:''};
export const PricingPresetFormDialog:React.FC<{open:boolean;preset?:PricingPreset|null;onClose:()=>void}>=({open,preset,onClose})=>{
 const create=useCreatePricingPreset(),update=useUpdatePricingPreset();const[form,setForm]=useState(empty);const[errors,setErrors]=useState<Record<string,string>>({});
 useEffect(()=>{if(!open)return;setForm(preset?{name:preset.name,productType:preset.productType??'',expensePercent:preset.expensePercent,profitPercent:preset.profitPercent,discountBufferPercent:preset.discountBufferPercent,installmentMarkupPercent:preset.installmentMarkupPercent,downPaymentPercent:preset.downPaymentPercent,defaultInstallmentMonths:String(preset.defaultInstallmentMonths),calculationMode:preset.calculationMode,roundingMode:preset.roundingMode,notes:preset.notes??'',sampleCost:'100.00',reason:'',accountPassword:''}:empty);setErrors({});},[open,preset]);
 const sensitive=useMemo(()=>!preset||formulaFields.some(field=>String(form[field])!==String(preset[field==='defaultInstallmentMonths'?field:field])),[form,preset]);
 const calculation=usePricingCalculation(form.sampleCost?{costPrice:form.sampleCost,installmentMonths:/^\d+$/.test(form.defaultInstallmentMonths)?Number(form.defaultInstallmentMonths):undefined,overrides:{expensePercent:form.expensePercent,profitPercent:form.profitPercent,discountBufferPercent:form.discountBufferPercent,installmentMarkupPercent:form.installmentMarkupPercent,downPaymentPercent:form.downPaymentPercent,calculationMode:form.calculationMode,roundingMode:form.roundingMode}}:null);
 const set=(field:keyof PricingPresetFormValues,value:string)=>{setForm(current=>({...current,[field]:value}));setErrors(current=>({...current,[field]:''}));};
 const submit=(event:FormEvent)=>{event.preventDefault();const parsed=pricingPresetFormSchema.safeParse(form);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return;}if((!preset||sensitive)&&!form.accountPassword){setErrors(current=>({...current,accountPassword:'Account password is required'}));return;}const data=parsed.data;const input={name:data.name,productType:data.productType||null,expensePercent:data.expensePercent,profitPercent:data.profitPercent,discountBufferPercent:data.discountBufferPercent,installmentMarkupPercent:data.installmentMarkupPercent,downPaymentPercent:data.downPaymentPercent,defaultInstallmentMonths:Number(data.defaultInstallmentMonths),calculationMode:data.calculationMode,roundingMode:data.roundingMode,notes:data.notes||null,reason:data.reason,accountPassword:data.accountPassword||undefined};if(preset)update.mutate({id:preset.id,input},{onSuccess:()=>{toast.success('Pricing preset updated / تم تعديل صيغة التسعير');onClose();}});else create.mutate({...input,accountPassword:data.accountPassword},{onSuccess:()=>{toast.success('Pricing preset created / تم إنشاء صيغة التسعير');onClose();}});};
 const pending=create.isPending||update.isPending;
 return <Modal isOpen={open} onClose={onClose} title={preset?'Edit Pricing Preset / تعديل صيغة التسعير':pricingLabels.createPreset} maxWidth="max-w-4xl"><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label={pricingLabels.presetName} value={form.name} set={v=>set('name',v)} error={errors.name} auto/><Field label={pricingLabels.productType} value={form.productType} set={v=>set('productType',v)} error={errors.productType} auto/>{percentFields.map(field=><Field key={field} label={pricingLabels[field]} value={String(form[field])} set={v=>set(field,v)} error={errors[field]} suffix="%"/>)}<Field label={pricingLabels.installmentMonths} value={form.defaultInstallmentMonths} set={v=>set('defaultInstallmentMonths',v)} error={errors.defaultInstallmentMonths}/><Select label={pricingLabels.calculationMode} value={form.calculationMode} set={v=>set('calculationMode',v)} options={[['COMPOUND',pricingLabels.compound],['SIMPLE',pricingLabels.simple]]}/><Select label={pricingLabels.roundingMode} value={form.roundingMode} set={v=>set('roundingMode',v)} options={[['NONE','None / بدون'],['NEAREST_0_50','Nearest 0.50'],['NEAREST_1','Nearest 1'],['CEIL_1','Round up to 1']]}/><Field label={pricingLabels.notes} value={form.notes} set={v=>set('notes',v)} auto area className="sm:col-span-2"/><Field label="Reason / السبب" value={form.reason} set={v=>set('reason',v)} error={errors.reason} auto area/><Field label="Account Password / كلمة مرور الحساب" value={form.accountPassword} set={v=>set('accountPassword',v)} error={errors.accountPassword} type="password"/></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(280px,0.8fr)]"><Field label="Sample Cost / تكلفة تجريبية" value={form.sampleCost} set={v=>set('sampleCost',v)} error={errors.sampleCost}/><PricingPreviewCard preview={calculation.data} loading={calculation.isLoading} stale={calculation.isFetching} costPrice={form.sampleCost} percents={form}/></div><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel / إلغاء</button><button disabled={pending} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending?'Saving…':'Save / حفظ'}</button></div></form></Modal>;
};
const Field:React.FC<{label:string;value:string;set:(v:string)=>void;error?:string;auto?:boolean;area?:boolean;suffix?:string;type?:string;className?:string}>=({label,value,set,error,auto,area,suffix,type='text',className=''})=><label className={`block text-sm font-medium text-slate-700 ${className}`}>{label}<span className="relative mt-1 block">{area?<textarea dir={auto?'auto':'ltr'} value={value} onChange={e=>set(e.target.value)} className="user-text-input min-h-20 w-full rounded-lg border border-slate-300 px-3 py-2"/>:<input dir={auto?'auto':'ltr'} type={type} inputMode={suffix?'decimal':'text'} value={value} onChange={e=>set(e.target.value)} className="user-text-input w-full rounded-lg border border-slate-300 px-3 py-2 pr-8"/>}{suffix&&<span className="absolute right-3 top-2 text-slate-400">{suffix}</span>}</span>{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>;
const Select:React.FC<{label:string;value:string;set:(v:string)=>void;options:readonly(readonly[string,string])[]}>=({label,value,set,options})=><label className="block text-sm font-medium text-slate-700">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
