export const productLabels = {
  searchPlaceholder: 'Search products, notes, or specifications / بحث في المنتجات أو الملاحظات أو المواصفات',
  allBrands: 'All Brands / كل الماركات',
  anyBarcode: 'Any Barcode / أي باركود',
  withBarcode: 'With Barcode / مع باركود',
  withoutBarcode: 'Without Barcode / بدون باركود',
  anyStockStatus: 'Any stock status / أي حالة مخزون',
  anyTracking: 'Tracked and untracked / متتبع وغير متتبع',
  tracked: 'Tracked only / المتتبع فقط',
  untracked: 'Untracked only / غير المتتبع فقط',
  notInInventory: 'Not in inventory / خارج المخزون',
  moreFilters: 'More filters / مزيد من التصفية',
  resetFilters: 'Reset filters / إعادة ضبط',
  activeProducts: 'Active / النشطة',
  archivedProducts: 'Archived / المؤرشفة',
  viewDetails: 'View Details / عرض التفاصيل',
  noProducts: 'No products match these filters / لا توجد منتجات مطابقة',
  noProductsHint: 'Try a different search, or clear the filters to see the whole catalogue / جرّب بحثاً آخر أو أعد ضبط التصفية لعرض كل المنتجات',
  emptyCatalogue: 'No products yet / لا توجد منتجات بعد',
  emptyCatalogueHint: 'Add your first product to start building the catalogue / أضف أول منتج لبدء بناء دليل المنتجات',
  noArchivedProducts: 'Nothing archived / لا يوجد مؤرشف',
  noArchivedProductsHint: 'Archived products appear here so they can be restored / تظهر المنتجات المؤرشفة هنا ليتم استعادتها',
  loadFailed: 'Unable to load products / تعذر تحميل المنتجات',
  retry: 'Try again / إعادة المحاولة',
  totalProducts: 'Total / الإجمالي',
  showingProducts: 'Showing / المعروض',
  trackedProducts: 'Tracked / متتبع',
  lowStockProducts: 'Low stock / مخزون منخفض',
  outOfStockProducts: 'Out of stock / نفد المخزون',
  relatedJobs: 'Related Service Jobs / طلبات الصيانة المرتبطة',
  auditHistory: 'Audit History / سجل التعديلات',
  createdBy: 'Created By / أنشأه',
  updatedBy: 'Updated By / عدّله',
  reason: 'Reason / السبب',
  accountPassword: 'Account Password / كلمة مرور الحساب',
} as const;
