import React, { useState } from 'react';
import { Plus, Wrench } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { CreateServiceJobDialog } from '../../features/service/components/CreateServiceJobDialog';
import { ServiceJobsTable } from '../../features/service/components/ServiceJobsTable';
import { useServiceJobs } from '../../features/service/hooks/useServiceJobs';
import { ServiceJobFilters, ServiceRequestType, WarrantyStatus } from '../../features/service/types/service.types';
import { REQUEST_TYPE_LABELS, STATUS_LABELS, WARRANTY_LABELS } from '../../features/service/utils/service-labels';
import { businessLabels } from '../../shared/labels/business-labels';

export const ServiceJobsPage: React.FC = () => {
  const [params, setParams] = useSearchParams();
  const [createOpen, setCreateOpen] = useState(false);
  const filters: ServiceJobFilters = { search: params.get('search') || undefined, status: params.get('status') ? [params.get('status')!] : undefined, requestType: params.get('requestType') ? [params.get('requestType') as ServiceRequestType] : undefined, warrantyStatus: params.get('warrantyStatus') ? [params.get('warrantyStatus') as WarrantyStatus] : undefined, customerId: params.get('customerId') || undefined, dateFrom: params.get('dateFrom') || undefined, dateTo: params.get('dateTo') || undefined, sort: (params.get('sort') as ServiceJobFilters['sort']) || 'createdDesc', page: Number(params.get('page') || 1), pageSize: 25 };
  const jobs = useServiceJobs(filters);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.delete('page'); setParams(next); };
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><Wrench className="h-7 w-7 shrink-0 text-emerald-600" /><h1 className="text-2xl font-bold leading-tight text-slate-900">{businessLabels.service.maintenance}</h1></div><p className="mt-1 text-sm text-slate-500">Track repair jobs from intake through delivery / متابعة الصيانة من الاستلام حتى التسليم.</p></div><button onClick={() => setCreateOpen(true)} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-700 sm:w-auto"><Plus className="h-4 w-4 shrink-0" /> <span className="whitespace-normal text-center leading-snug">{businessLabels.service.newJob}</span></button></div>
    <section className="rounded-lg border border-slate-200 bg-white p-4"><div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-[minmax(24rem,2fr)_repeat(4,minmax(11rem,1fr))]"><input value={params.get('search') ?? ''} onChange={(e) => update('search', e.target.value)} placeholder="Job, customer, phone, product / الطلب، الزبون، الهاتف، المنتج" className="min-w-0 rounded-lg border border-slate-300 px-3 py-2 text-sm" /><select value={params.get('status') ?? ''} onChange={(e) => update('status', e.target.value)} className="min-w-0 rounded-lg border border-slate-300 px-2.5 py-2 text-sm"><option value="">Open Jobs / الطلبات المفتوحة</option><option value="OPEN">All Open / كل المفتوحة</option><option value="CLOSED">All Completed / كل المكتملة</option>{Object.entries(STATUS_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select value={params.get('requestType') ?? ''} onChange={(e) => update('requestType', e.target.value)} className="min-w-0 rounded-lg border border-slate-300 px-2.5 py-2 text-sm"><option value="">Any Request / أي طلب</option>{Object.entries(REQUEST_TYPE_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select value={params.get('warrantyStatus') ?? ''} onChange={(e) => update('warrantyStatus', e.target.value)} className="min-w-0 rounded-lg border border-slate-300 px-2.5 py-2 text-sm"><option value="">Any Warranty / أي كفالة</option>{Object.entries(WARRANTY_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select value={params.get('sort') ?? 'createdDesc'} onChange={(e) => update('sort', e.target.value)} className="min-w-0 rounded-lg border border-slate-300 px-2.5 py-2 text-sm"><option value="createdDesc">Newest First / الأحدث أولاً</option><option value="createdAsc">Oldest First / الأقدم أولاً</option><option value="statusAsc">Status / الحالة</option><option value="customerAsc">Customer / الزبون</option></select></div></section>
    {jobs.isLoading ? <div className="p-12 text-center text-slate-500">Loading service jobs...</div> : jobs.isError ? <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">Unable to load service jobs.</div> : jobs.data?.items.length ? <><ServiceJobsTable jobs={jobs.data.items} /><div className="flex items-center justify-between text-sm text-slate-600"><span>{jobs.data.pagination.totalItems} jobs</span><div className="flex gap-2"><button disabled={filters.page === 1} onClick={() => update('page', String((filters.page ?? 1)-1))} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={(filters.page ?? 1) >= jobs.data.pagination.totalPages} onClick={() => update('page', String((filters.page ?? 1)+1))} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div></div></> : <div className="rounded-lg border border-dashed border-slate-300 bg-white p-12 text-center"><Wrench className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 font-medium text-slate-700">No service jobs match these filters.</p></div>}
    <CreateServiceJobDialog isOpen={createOpen} onClose={() => setCreateOpen(false)} />
  </div>;
};
