import React from 'react';
import { ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { formatBusinessDate, formatMoney } from '../../customer-financial/utils/financial-format';
import { ServiceJob, resolveProductDisplay } from '../types/service.types';
import { getServiceJobAgeState } from '../utils/service-age';
import { REQUEST_TYPE_LABELS } from '../utils/service-labels';
import { ServiceJobAgeBadge } from './ServiceJobAgeBadge';
import { ServiceJobStatusChip } from './ServiceJobStatusChip';

export const ServiceJobsTable: React.FC<{ jobs: ServiceJob[] }> = ({ jobs }) => <>
  <div className="hidden overflow-x-auto rounded-lg border border-slate-200 bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-600"><tr>{['Job / الطلب','Customer / الزبون','Product / المنتج','Request / النوع','Status / الحالة','Created / التاريخ','Price / السعر',''].map((heading) => <th key={heading} className="whitespace-nowrap px-4 py-3 font-semibold">{heading || <span className="sr-only">Actions / الإجراءات</span>}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{jobs.map((job) => { const product = resolveProductDisplay(job); const overdue = getServiceJobAgeState(job.serviceCreatedDate, job.status)?.state === 'OVERDUE'; return <tr key={job.id} className={overdue ? 'bg-red-50/60 hover:bg-red-50' : 'hover:bg-slate-50'}><td className={`px-4 py-3 font-semibold text-slate-900 ${overdue ? 'border-l-4 border-red-500' : ''}`}>{job.jobNumber}</td><td className="px-4 py-3"><Link className="user-text font-medium text-slate-900 hover:text-emerald-700" dir="auto" to={`/customers/${job.customer.id}`}>{job.customer.name}</Link><p className="text-xs text-slate-500">{job.customer.phone}</p></td><td className="px-4 py-3"><p className="user-text font-medium" dir="auto">{product.name}</p>{product.model && <p className="user-text text-xs text-slate-500" dir="auto">{product.model}</p>}</td><td className="px-4 py-3">{REQUEST_TYPE_LABELS[job.requestType]}</td><td className="px-4 py-3"><ServiceJobStatusChip status={job.status} /></td><td className="whitespace-nowrap px-4 py-3"><div>{formatBusinessDate(job.serviceCreatedDate)}</div><ServiceJobAgeBadge serviceCreatedDate={job.serviceCreatedDate} status={job.status} /></td><td className="whitespace-nowrap px-4 py-3 font-medium">{job.finalPrice ? formatMoney(job.finalPrice) : job.estimatedPrice ? formatMoney(job.estimatedPrice) : '—'}</td><td className="px-4 py-3"><Link to={`/service/${job.id}`} aria-label={`Open ${job.jobNumber}`} className="inline-flex rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-100"><ExternalLink className="h-4 w-4" /></Link></td></tr>; })}</tbody></table></div>
  <div className="space-y-3 md:hidden">{jobs.map((job) => { const product = resolveProductDisplay(job); const overdue = getServiceJobAgeState(job.serviceCreatedDate, job.status)?.state === 'OVERDUE'; return <article key={job.id} className={`rounded-lg border bg-white p-4 shadow-sm ${overdue ? 'border-red-300 bg-red-50/60' : 'border-slate-200'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{job.jobNumber}</p><p className="user-text text-sm text-slate-600" dir="auto">{job.customer.name} · {job.customer.phone}</p></div><ServiceJobStatusChip status={job.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Product / المنتج</dt><dd className="user-text font-medium" dir="auto">{product.name}</dd></div><div><dt className="text-xs text-slate-500">Created / التاريخ</dt><dd>{formatBusinessDate(job.serviceCreatedDate)}</dd><ServiceJobAgeBadge serviceCreatedDate={job.serviceCreatedDate} status={job.status} /></div><div><dt className="text-xs text-slate-500">Request / النوع</dt><dd>{REQUEST_TYPE_LABELS[job.requestType]}</dd></div><div><dt className="text-xs text-slate-500">Price / السعر</dt><dd>{job.finalPrice ? formatMoney(job.finalPrice) : job.estimatedPrice ? formatMoney(job.estimatedPrice) : '—'}</dd></div></dl><Link to={`/service/${job.id}`} className="mt-4 inline-flex items-center gap-2 font-medium text-emerald-700">View Details / عرض التفاصيل <ExternalLink className="h-4 w-4" /></Link></article>; })}</div>
</>;
