import React,{useEffect,useState} from 'react';
import toast from 'react-hot-toast';
import { Modal } from '../../../components/ui/Modal';
import { businessLabels } from '../../../shared/labels/business-labels';
import { Supplier } from '../types/supplier.types';
import { useSupplierMutations } from '../hooks/useSupplierMutations';
import { normalizeFinancialError } from '../../customer-financial/utils/financial-form-errors';

export const SupplierFormDialog:React.FC<{open:boolean;supplier?:Supplier|null;onClose:()=>void}>=({open,supplier,onClose})=>{const mutations=useSupplierMutations();const mutation=supplier?mutations.update:mutations.create;const [form,setForm]=useState({name:'',phone:'',companyName:'',secondaryPhone:'',email:'',notes:'',reason:'',accountPassword:''});
 useEffect(()=>{setForm({name:supplier?.name??'',phone:supplier?.phone??'',companyName:supplier?.companyName??'',secondaryPhone:supplier?.secondaryPhone??'',email:supplier?.email??'',notes:supplier?.notes??'',reason:'',accountPassword:''});},[supplier,open]);
 const set=(key:string)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setForm(v=>({...v,[key]:e.target.value}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const base={name:form.name,phone:form.phone,companyName:form.companyName||null,secondaryPhone:form.secondaryPhone||null,email:form.email||null,notes:form.notes||null};if(supplier)await mutations.update.mutateAsync({id:supplier.id,input:{...base,reason:form.reason||undefined,accountPassword:form.accountPassword||undefined}});else await mutations.create.mutateAsync(base);onClose();}catch(error){toast.error(normalizeFinancialError(error).message);}};
 return <Modal isOpen={open} onClose={onClose} title={supplier?businessLabels.supplier.edit:businessLabels.supplier.add} maxWidth="max-w-2xl"><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label={businessLabels.supplier.name} required value={form.name} onChange={set('name')}/><Field label={businessLabels.supplier.phone} required value={form.phone} onChange={set('phone')}/><Field label={businessLabels.supplier.company} value={form.companyName} onChange={set('companyName')}/><Field label={businessLabels.supplier.secondaryPhone} value={form.secondaryPhone} onChange={set('secondaryPhone')}/><Field label={businessLabels.supplier.email} type="email" value={form.email} onChange={set('email')}/></div><label className="block text-sm font-semibold text-slate-700">{businessLabels.supplier.notes}<textarea dir="auto" className="user-text-input mt-1 min-h-24 w-full rounded-md border border-slate-300 p-3 font-normal" value={form.notes} onChange={set('notes')}/></label>{supplier&&<div className="grid gap-4 border-t border-slate-200 pt-4 sm:grid-cols-2"><Field label={businessLabels.supplier.reason} value={form.reason} onChange={set('reason')}/><Field label={businessLabels.supplier.accountPassword} type="password" value={form.accountPassword} onChange={set('accountPassword')}/></div>}<button disabled={mutation.isPending} className="w-full rounded-md bg-emerald-600 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{mutation.isPending?'Saving... / جارٍ الحفظ':businessLabels.common.save}</button></form></Modal>};
const Field:React.FC<React.InputHTMLAttributes<HTMLInputElement>&{label:string}>=({label,...props})=><label className="block text-sm font-semibold text-slate-700">{label}<input {...props} dir="auto" className="user-text-input mt-1 w-full rounded-md border border-slate-300 px-3 py-2 font-normal"/></label>;
