export const businessLabels = {
  common: {
    add: 'Add / إضافة',
    edit: 'Edit / تعديل',
    save: 'Save / حفظ',
    saveChanges: 'Save changes / حفظ التعديلات',
    cancel: 'Cancel / إلغاء',
    search: 'Search / بحث',
    actions: 'Actions / الإجراءات',
    notes: 'Notes / ملاحظات',
    status: 'Status / الحالة',
    created: 'Created / تاريخ الإنشاء',
    customer: 'Customer / الزبون',
  },
  customer: {
    profile: 'Customer Profile / ملف الزبون',
    add: 'Add Customer / إضافة زبون',
    edit: 'Edit Customer / تعديل الزبون',
    name: 'Customer Name / اسم الزبون',
    phone: 'Phone / رقم الهاتف',
    address: 'Address / العنوان',
    contactDetails: 'Contact Details / معلومات الاتصال',
    accountInformation: 'Account Information / معلومات الحساب',
    active: 'Active / نشط',
    inactive: 'Inactive / غير نشط',
    title: 'Customers / الزبائن',
    outstanding: 'Outstanding / الرصيد المتبقي',
    overdue: 'Overdue / متأخر',
    activeDebts: 'Debts / الديون',
    activePlans: 'Plans / الخطط',
    lastPayment: 'Last Payment / آخر دفعة',
    nextDue: 'Next Due / الاستحقاق القادم',
    settled: 'Settled / مسدد',
    viewProfile: 'View profile / عرض الملف',
    notFound: 'No customers found / لم يتم العثور على زبائن',
    matchedInNotes: 'Matched in notes / مطابقة في الملاحظات',
    searchPlaceholder: 'Search customers / البحث عن زبائن',
    recentSearches: 'Recent searches / عمليات البحث الأخيرة',
    clearHistory: 'Clear history / مسح السجل',
    didYouMean: 'Did you mean? / هل تقصد؟',
    totalPaid: 'Total paid / مجموع المدفوع',
    totalDebt: 'Total debt / إجمالي الديون',
    addDebt: 'Add debt / إضافة دين',
    recordPayment: 'Record payment / تسجيل دفعة',
    addInstallmentPlan: 'Add installment plan / إضافة خطة تقسيط',
    viewLedger: 'View ledger / عرض دفتر الحسابات',
    copyPhone: 'Copy phone / نسخ الهاتف',
    thisMonth: 'This month / هذا الشهر',
  },
  financial: {
    debt: 'Debt / دين',
    debts: 'Debts / ديون',
    addDebt: 'Add Debt / إضافة دين',
    singleDebt: 'Single debt / دين مفرد',
    prepaidPurchase: 'Prepaid Purchase / شراء بالدفع المسبق',
    itemName: 'Item Name / اسم السلعة',
    fullAmount: 'Full Amount / المبلغ الكامل',
    initialPayment: 'Payment / الدفعة',
    payment: 'Payment / دفعة',
    payments: 'Payments / دفعات',
    recordPayment: 'Record Payment / تسجيل دفعة',
    receivePayment: 'Receive Payment / استلام دفعة',
    installmentPlan: 'Installment Plan / خطة تقسيط',
    installmentPlans: 'Installment Plans / خطط تقسيط',
    installment: 'Installment / قسط',
    total: 'Total / المجموع',
    amount: 'Amount / المبلغ',
    paid: 'Paid / المدفوع',
    remaining: 'Remaining / المتبقي',
    balance: 'Balance / الرصيد',
    adminDebt: 'Admin Debt / دين على الإدارة',
    outstanding: 'Outstanding / المتبقي للدفع',
    dueDate: 'Due Date / تاريخ الاستحقاق',
    paymentDate: 'Payment Date / تاريخ الدفعة',
    paymentMethod: 'Payment Method / طريقة الدفع',
    description: 'Description / الوصف',
    reference: 'Reference / المرجع',
  },
  prepaid: {
    title: 'Prepaid Purchases / المشتريات المدفوعة مسبقاً',
    navTitle: 'Prepaid / المدفوع مسبقاً',
    item: 'Item / الصنف',
    fullPrice: 'Full Price / السعر الكامل',
    paid: 'Paid / المدفوع',
    adminDebt: 'We Owe / علينا',
    remaining: 'Remaining / المتبقي',
    status: 'Status / الحالة',
    statusPending: 'Prepaid / مدفوع مسبقاً',
    statusDelivered: 'Delivered / تم التسليم',
    statusCancelled: 'Cancelled / ملغى',
    markDelivered: 'Mark Delivered / تسجيل التسليم',
    revertDelivery: 'Revert Delivery / إلغاء التسليم',
    remainderDueDate: 'Due Date for Remaining / تاريخ استحقاق المتبقي',
    deliveryNotes: 'Delivery Notes / ملاحظات التسليم',
    deliveredOn: 'Delivered On / تاريخ التسليم',
    totalWeOwe: 'Total We Owe / إجمالي ما علينا',
    awaitingDelivery: 'Awaiting Delivery / بانتظار التسليم',
    fullyPaidOnly: 'Fully paid only / المدفوع بالكامل فقط',
    viewDetails: 'View Details / عرض التفاصيل',
    editPurchase: 'Edit Purchase / تعديل الشراء',
    recordPayment: 'Record Payment / تسجيل دفعة',
    cancelPurchase: 'Cancel Purchase / إلغاء الشراء',
    reason: 'Reason / السبب',
    accountPassword: 'Account Password / كلمة مرور الحساب',
    empty: 'No prepaid purchases / لا توجد مشتريات مدفوعة مسبقاً',
    balance: 'Prepaid Balance / الرصيد المسبق',
    history: 'Prepaid History / سجل المدفوعات المسبقة',
    addBill: 'Add Prepaid Bill / إضافة فاتورة مسبقة',
    bills: 'Bills / الفواتير',
    billHistory: 'Bill History / سجل الفواتير',
    receiptNumber: 'Receipt / Bill No. / رقم الإيصال',
    recordedBy: 'Recorded By / سجلها',
    createdBy: 'Created By / أنشأها',
    voidedBill: 'Voided / ملغاة',
    noBills: 'No bills recorded yet / لم تسجل أي فاتورة بعد',
    customerEmpty: 'No prepaid purchases for this customer / لا توجد مشتريات مسبقة لهذا الزبون',
  },
  ledger: {
    title: 'Ledger / دفتر الحسابات',
    view: 'Ledger View / عرض دفتر الحسابات',
    type: 'Type / النوع',
    includeCompleted: 'Include Completed / إظهار المكتمل',
    includeCancelled: 'Include Cancelled / إظهار الملغى',
    customerSearch: 'Customer Search / بحث عن زبون',
  },
  service: {
    maintenance: 'Maintenance & Service / الصيانة والخدمة',
    job: 'Service Job / طلب صيانة',
    jobs: 'Service Jobs / طلبات الصيانة',
    newJob: 'New Service Job / طلب صيانة جديد',
    editJob: 'Edit Service Job / تعديل طلب الصيانة',
    requestType: 'Request Type / نوع الطلب',
    issueDescription: 'Issue Description / وصف العطل',
    requestedPart: 'Requested Part / القطعة المطلوبة',
    warranty: 'Warranty / الكفالة',
    product: 'Product / المنتج',
    routing: 'Routing / مسار الصيانة',
    company: 'Company / الشركة',
  },
  product: {
    products: 'Products / المنتجات',
    name: 'Product Name / اسم المنتج',
    model: 'Model / الموديل',
    brand: 'Brand / الماركة',
    barcode: 'Barcode / الباركود',
    price: 'Price / السعر',
    discountAmount: 'Discount Amount / قيمة الخصم',
    netPrice: 'Net Price / السعر الصافي',
    notes: 'Product Notes / ملاحظات المنتج',
    status: 'Status / الحالة',
    active: 'Active / نشط',
    archived: 'Archived / مؤرشف',
    addProduct: 'Add Product / إضافة منتج',
    editProduct: 'Edit Product / تعديل المنتج',
    archiveProduct: 'Archive Product / أرشفة المنتج',
    restoreProduct: 'Restore Product / استعادة المنتج',
    duplicateWarning: 'A similar product already exists / يوجد منتج مشابه',
    printLabel: 'Print Label / طباعة الملصق',
  },
  system: {
    backendConnected: 'Backend Connected / الخادم متصل',
    backendDisconnected: 'Backend Disconnected / الخادم غير متصل',
    databaseConnected: 'Database Connected / قاعدة البيانات متصلة',
    databaseUnavailable: 'Database Unavailable / قاعدة البيانات غير متاحة',
    databaseUnknown: 'Database Status Unknown / حالة قاعدة البيانات غير معروفة',
    lanScannerAvailable: 'LAN Scanner Available / ماسح الشبكة متاح',
    lanScannerOff: 'LAN Scanner Off / ماسح الشبكة متوقف',
    internetOnline: 'Internet Online / الإنترنت متصل',
    internetOffline: 'Internet Offline / الإنترنت غير متصل',
    localSystemUnaffected: 'Local system unaffected / النظام المحلي يعمل',
  },
  scanner: {
    scannerMode: 'Scanner Mode / وضع المسح',
    scanProduct: 'Scan Product / مسح المنتج',
    recentScans: 'Recent Scans / عمليات المسح الأخيرة',
    noRecentScans: 'No scans yet / لا توجد عمليات مسح',
    clearScans: 'Clear / مسح السجل',
    productFound: 'Product Found / تم العثور على المنتج',
    openProduct: 'Open Product / فتح المنتج',
    productNotFound: 'Product Not Found / لم يتم العثور على المنتج',
    invalidCode: 'Unreadable Code / رمز غير صالح',
    lookupFailed: 'Scan lookup failed / تعذر تنفيذ المسح',
    searching: 'Looking up / جارٍ البحث',
    archivedProduct: 'Archived Product / منتج مؤرشف',
    matchedByBarcode: 'Matched by barcode / مطابقة بالباركود',
    matchedBySku: 'Matched by SKU / مطابقة برمز المنتج',
    alsoMatchedSku: 'This code is also another product SKU / هذا الرمز هو أيضاً رمز منتج آخر',
    pcScanner: 'PC Scanner / ماسح الجهاز',
    phoneScanner: 'Phone Scanner / ماسح الهاتف',
    hub: 'Scanner Hub / مركز المسح',
    hubSubtitle: 'Scan products here, or from a phone on the shop Wi-Fi / امسح المنتجات من الجهاز أو من هاتف على شبكة المحل',
    lanMode: 'Mobile Scanner / ماسح الهاتف',
    enableLan: 'Turn On / تشغيل',
    disableLan: 'Turn Off / إيقاف',
    disableLanTitle: 'Turn off mobile scanner / إيقاف ماسح الهاتف',
    disableLanWarning: 'Every paired phone will be disconnected and must pair again / سيتم فصل كل الهواتف المرتبطة وستحتاج إلى إعادة الربط',
    phoneUrl: 'Phone address / عنوان الهاتف',
    copyUrl: 'Copy / نسخ',
    copied: 'Copied / تم النسخ',
    otherAddresses: 'Other network adapters / محولات شبكة أخرى',
    addressHint: 'Open this address on a phone connected to the same Wi-Fi / افتح هذا العنوان على هاتف متصل بنفس الشبكة',
    pairingCode: 'Pairing code / رمز الربط',
    generateCode: 'Generate Code / إنشاء رمز',
    codeExpiresIn: 'Expires in / ينتهي خلال',
    codeExpired: 'Expired - generate a new one / انتهى - أنشئ رمزاً جديداً',
    pairedDevices: 'Paired Devices / الأجهزة المرتبطة',
    noPairedDevices: 'No phones paired / لا توجد هواتف مرتبطة',
    deviceName: 'Device / الجهاز',
    lastSeen: 'Last seen / آخر ظهور',
    revoke: 'Revoke / إلغاء',
    firewallTitle: 'If the phone cannot reach this PC / إذا تعذر وصول الهاتف',
    adminOnly: 'Only an administrator can change these settings / يمكن للمدير فقط تغيير هذه الإعدادات',
  },
  supplier: {
    title: 'Suppliers / المورّدين', singular: 'Supplier / المورّد', add: 'Add Supplier / إضافة مورّد',
    edit: 'Edit Supplier / تعديل مورّد', remove: 'Remove Supplier / إزالة مورّد', archive: 'Archive / أرشفة',
    restore: 'Restore / استعادة', name: 'Supplier Name / اسم المورّد', phone: 'Phone / رقم الهاتف',
    secondaryPhone: 'Secondary Phone / رقم هاتف إضافي', company: 'Company Name / اسم الشركة',
    email: 'Email / البريد الإلكتروني', notes: 'Notes / ملاحظات', totalOwed: 'Total Owed / إجمالي المستحق',
    totalPaid: 'Total Paid / إجمالي المدفوع', totalCredit: 'Total Credit / إجمالي الرصيد', balance: 'Balance / الرصيد',
    ledgerTitle: 'Supplier Ledger / دفتر حسابات المورّدين', addTransaction: 'Add Transaction / إضافة حركة',
    transaction: 'Transaction / حركة', amount: 'Amount / المبلغ', date: 'Transaction Date / تاريخ الحركة',
    description: 'Description / الوصف', reference: 'Reference / المرجع', reason: 'Reason / السبب',
    accountPassword: 'Account Password / كلمة مرور الحساب', includeRemoved: 'Include Removed / إظهار المحذوفة',
  },
} as const;

export const businessValidationMessages = {
  customerNameRequired: 'Customer name is required / اسم الزبون مطلوب',
  phoneRequired: 'Phone is required / رقم الهاتف مطلوب',
  amountRequired: 'Amount is required / المبلغ مطلوب',
  dateRequired: 'Date is required / التاريخ مطلوب',
  dueDateRequired: 'Due date is required / تاريخ الاستحقاق مطلوب',
  productNameRequired: 'Product name is required / اسم المنتج مطلوب',
  modelRequired: 'Model is required / الموديل مطلوب',
} as const;
