export const businessLabels = {
  common: {
    add: 'Add / إضافة',
    edit: 'Edit / تعديل',
    save: 'Save / حفظ',
    saveChanges: 'Save changes / حفظ التعديلات',
    cancel: 'Cancel / إلغاء',
    search: 'Search / بحث',
    actions: 'Actions / الإجراءات',
    notes: 'Notes / ملاحظات',
    status: 'Status / الحالة',
    created: 'Created / تاريخ الإنشاء',
    customer: 'Customer / الزبون',
  },
  customer: {
    profile: 'Customer Profile / ملف الزبون',
    add: 'Add Customer / إضافة زبون',
    edit: 'Edit Customer / تعديل الزبون',
    name: 'Customer Name / اسم الزبون',
    phone: 'Phone / رقم الهاتف',
    address: 'Address / العنوان',
    contactDetails: 'Contact Details / معلومات الاتصال',
    accountInformation: 'Account Information / معلومات الحساب',
    active: 'Active / نشط',
    inactive: 'Inactive / غير نشط',
  },
  financial: {
    debt: 'Debt / دين',
    debts: 'Debts / ديون',
    addDebt: 'Add Debt / إضافة دين',
    singleDebt: 'Single debt / دين مفرد',
    prepaidPurchase: 'Prepaid Purchase / شراء بالدفع المسبق',
    itemName: 'Item Name / اسم السلعة',
    fullAmount: 'Full Amount / المبلغ الكامل',
    initialPayment: 'Payment / الدفعة',
    payment: 'Payment / دفعة',
    payments: 'Payments / دفعات',
    recordPayment: 'Record Payment / تسجيل دفعة',
    receivePayment: 'Receive Payment / استلام دفعة',
    installmentPlan: 'Installment Plan / خطة تقسيط',
    installmentPlans: 'Installment Plans / خطط تقسيط',
    installment: 'Installment / قسط',
    total: 'Total / المجموع',
    amount: 'Amount / المبلغ',
    paid: 'Paid / المدفوع',
    remaining: 'Remaining / المتبقي',
    balance: 'Balance / الرصيد',
    adminDebt: 'Admin Debt / دين على الإدارة',
    outstanding: 'Outstanding / المتبقي للدفع',
    dueDate: 'Due Date / تاريخ الاستحقاق',
    paymentDate: 'Payment Date / تاريخ الدفعة',
    paymentMethod: 'Payment Method / طريقة الدفع',
    description: 'Description / الوصف',
    reference: 'Reference / المرجع',
  },
  prepaid: {
    title: 'Prepaid Purchases / المشتريات المدفوعة مسبقاً',
    navTitle: 'Prepaid / المدفوع مسبقاً',
    item: 'Item / الصنف',
    fullPrice: 'Full Price / السعر الكامل',
    paid: 'Paid / المدفوع',
    adminDebt: 'We Owe / علينا',
    remaining: 'Remaining / المتبقي',
    status: 'Status / الحالة',
    statusPending: 'Prepaid / مدفوع مسبقاً',
    statusDelivered: 'Delivered / تم التسليم',
    statusCancelled: 'Cancelled / ملغى',
    markDelivered: 'Mark Delivered / تسجيل التسليم',
    revertDelivery: 'Revert Delivery / إلغاء التسليم',
    remainderDueDate: 'Due Date for Remaining / تاريخ استحقاق المتبقي',
    deliveryNotes: 'Delivery Notes / ملاحظات التسليم',
    deliveredOn: 'Delivered On / تاريخ التسليم',
    totalWeOwe: 'Total We Owe / إجمالي ما علينا',
    awaitingDelivery: 'Awaiting Delivery / بانتظار التسليم',
    fullyPaidOnly: 'Fully paid only / المدفوع بالكامل فقط',
    viewDetails: 'View Details / عرض التفاصيل',
    reason: 'Reason / السبب',
    accountPassword: 'Account Password / كلمة مرور الحساب',
    empty: 'No prepaid purchases / لا توجد مشتريات مدفوعة مسبقاً',
  },
  ledger: {
    title: 'Ledger / دفتر الحسابات',
    view: 'Ledger View / عرض دفتر الحسابات',
    type: 'Type / النوع',
    includeCompleted: 'Include Completed / إظهار المكتمل',
    includeCancelled: 'Include Cancelled / إظهار الملغى',
    customerSearch: 'Customer Search / بحث عن زبون',
  },
  service: {
    maintenance: 'Maintenance & Service / الصيانة والخدمة',
    job: 'Service Job / طلب صيانة',
    jobs: 'Service Jobs / طلبات الصيانة',
    newJob: 'New Service Job / طلب صيانة جديد',
    editJob: 'Edit Service Job / تعديل طلب الصيانة',
    requestType: 'Request Type / نوع الطلب',
    issueDescription: 'Issue Description / وصف العطل',
    requestedPart: 'Requested Part / القطعة المطلوبة',
    warranty: 'Warranty / الكفالة',
    product: 'Product / المنتج',
    routing: 'Routing / مسار الصيانة',
    company: 'Company / الشركة',
  },
  product: {
    products: 'Products / المنتجات',
    name: 'Product Name / اسم المنتج',
    model: 'Model / الموديل',
    brand: 'Brand / الماركة',
    barcode: 'Barcode / الباركود',
    price: 'Price / السعر',
    discountAmount: 'Discount Amount / قيمة الخصم',
    netPrice: 'Net Price / السعر الصافي',
    notes: 'Product Notes / ملاحظات المنتج',
    status: 'Status / الحالة',
    active: 'Active / نشط',
    archived: 'Archived / مؤرشف',
    addProduct: 'Add Product / إضافة منتج',
    editProduct: 'Edit Product / تعديل المنتج',
    archiveProduct: 'Archive Product / أرشفة المنتج',
    restoreProduct: 'Restore Product / استعادة المنتج',
    duplicateWarning: 'A similar product already exists / يوجد منتج مشابه',
    printLabel: 'Print Label / طباعة الملصق',
  },
  supplier: {
    title: 'Suppliers / المورّدين', singular: 'Supplier / المورّد', add: 'Add Supplier / إضافة مورّد',
    edit: 'Edit Supplier / تعديل مورّد', remove: 'Remove Supplier / إزالة مورّد', archive: 'Archive / أرشفة',
    restore: 'Restore / استعادة', name: 'Supplier Name / اسم المورّد', phone: 'Phone / رقم الهاتف',
    secondaryPhone: 'Secondary Phone / رقم هاتف إضافي', company: 'Company Name / اسم الشركة',
    email: 'Email / البريد الإلكتروني', notes: 'Notes / ملاحظات', totalOwed: 'Total Owed / إجمالي المستحق',
    totalPaid: 'Total Paid / إجمالي المدفوع', totalCredit: 'Total Credit / إجمالي الرصيد', balance: 'Balance / الرصيد',
    ledgerTitle: 'Supplier Ledger / دفتر حسابات المورّدين', addTransaction: 'Add Transaction / إضافة حركة',
    transaction: 'Transaction / حركة', amount: 'Amount / المبلغ', date: 'Transaction Date / تاريخ الحركة',
    description: 'Description / الوصف', reference: 'Reference / المرجع', reason: 'Reason / السبب',
    accountPassword: 'Account Password / كلمة مرور الحساب', includeRemoved: 'Include Removed / إظهار المحذوفة',
  },
} as const;

export const businessValidationMessages = {
  customerNameRequired: 'Customer name is required / اسم الزبون مطلوب',
  phoneRequired: 'Phone is required / رقم الهاتف مطلوب',
  amountRequired: 'Amount is required / المبلغ مطلوب',
  dateRequired: 'Date is required / التاريخ مطلوب',
  dueDateRequired: 'Due date is required / تاريخ الاستحقاق مطلوب',
  productNameRequired: 'Product name is required / اسم المنتج مطلوب',
  modelRequired: 'Model is required / الموديل مطلوب',
} as const;
