import { NextFunction, Request, Response } from 'express';
import { SupplierTransactionsService } from './supplier-transactions.service';
import { CreateSupplierTransactionInput, SupplierLedgerQueryInput, SupplierTransactionActionInput, SupplierTransactionListQueryInput, UpdateSupplierTransactionInput } from './supplier-transactions.validator';

const context = (req: { headers: Request['headers']; ip?: string }) => ({ requestId: typeof req.headers['x-request-id'] === 'string' ? req.headers['x-request-id'] : null, ipAddress: req.ip ?? null });
export class SupplierTransactionsController {
  static async create(req: Request<{ supplierId: string }, unknown, CreateSupplierTransactionInput>, res: Response, next: NextFunction) { try { res.status(201).json({ success: true, data: await SupplierTransactionsService.create(req.params.supplierId, req.body, req.user!, context(req)) }); } catch (e) { next(e); } }
  static async listForSupplier(req: Request<{ supplierId: string }>, res: Response, next: NextFunction) { try { const r = await SupplierTransactionsService.listForSupplier(req.params.supplierId, req.query as unknown as SupplierTransactionListQueryInput); res.json({ success: true, data: r.items, meta: { pagination: { page: r.page, pageSize: r.pageSize, totalItems: r.total, totalPages: Math.ceil(r.total/r.pageSize) } } }); } catch (e) { next(e); } }
  static async list(req: Request, res: Response, next: NextFunction) { try { const r = await SupplierTransactionsService.list(req.query as unknown as SupplierLedgerQueryInput); res.json({ success: true, data: r.items, meta: { pagination: { page: r.page, pageSize: r.pageSize, totalItems: r.total, totalPages: Math.ceil(r.total/r.pageSize) } } }); } catch (e) { next(e); } }
  static async get(req: Request<{ transactionId: string }>, res: Response, next: NextFunction) { try { res.json({ success: true, data: await SupplierTransactionsService.get(req.params.transactionId) }); } catch (e) { next(e); } }
  static async update(req: Request<{ transactionId: string }, unknown, UpdateSupplierTransactionInput>, res: Response, next: NextFunction) { try { res.json({ success: true, data: await SupplierTransactionsService.update(req.params.transactionId, req.body, req.user!, context(req)) }); } catch (e) { next(e); } }
  static async remove(req: Request<{ transactionId: string }, unknown, SupplierTransactionActionInput>, res: Response, next: NextFunction) { try { res.json({ success: true, data: await SupplierTransactionsService.remove(req.params.transactionId, req.body, req.user!, context(req)) }); } catch (e) { next(e); } }
  static async restore(req: Request<{ transactionId: string }, unknown, SupplierTransactionActionInput>, res: Response, next: NextFunction) { try { res.json({ success: true, data: await SupplierTransactionsService.restore(req.params.transactionId, req.body, req.user!, context(req)) }); } catch (e) { next(e); } }
  static async ledger(req: Request, res: Response, next: NextFunction) { try { res.json({ success: true, data: await SupplierTransactionsService.ledger(req.query as unknown as SupplierLedgerQueryInput) }); } catch (e) { next(e); } }
}
