import { Router } from 'express';
import { requireAccountPassword } from '../../../middleware/admin-password.middleware';
import { validate } from '../../../middleware/validate.middleware';
import { requirePricingAdmin } from '../../pricing/authorization/pricing-policy';
import { FeatureIconController } from './feature-icon.controller';
import { archiveFeatureIconSchema, createFeatureIconSchema, featureIconListQuerySchema, featureIconParamsSchema, updateFeatureIconSchema } from './feature-icon.validator';
export const featureIconRoutes = Router();
featureIconRoutes.get('/', validate(featureIconListQuerySchema, 'query'), FeatureIconController.list);
featureIconRoutes.post('/', requirePricingAdmin, requireAccountPassword, validate(createFeatureIconSchema), FeatureIconController.create);
featureIconRoutes.patch('/:featureIconId', requirePricingAdmin, requireAccountPassword, validate(featureIconParamsSchema, 'params'), validate(updateFeatureIconSchema), FeatureIconController.update);
featureIconRoutes.post('/:featureIconId/archive', requirePricingAdmin, requireAccountPassword, validate(featureIconParamsSchema, 'params'), validate(archiveFeatureIconSchema), FeatureIconController.archive);
