import { CheckCircle2, ChevronLeft, ChevronRight, Scale, TriangleAlert } from 'lucide-react';
import { formatMoney, formatSignedMoney } from '../../../customer-financial/utils/financial-format';
import { dashboardLabels } from '../../config/dashboard-labels';
import type { MonthEndData, MonthEndMovement } from '../../types';
import { DebtMovementChart } from '../charts/DebtMovementChart';
import { DashboardSection } from '../layout/DashboardSection';
import { SectionState } from './SectionState';

export function MonthEndSnapshot({ month, onMonthChange, data, isLoading, isError, onRetry }: { month: string; onMonthChange: (month: string) => void; data?: MonthEndData; isLoading: boolean; isError: boolean; onRetry: () => void }) {
  const action = <div className="flex items-center gap-1"><button className="dashboard-icon-button" onClick={() => onMonthChange(addMonth(month, -1))} aria-label="Previous month"><ChevronLeft className="h-4 w-4" /></button><input aria-label="Month end month" type="month" value={month} onChange={(event) => onMonthChange(event.target.value)} className="dashboard-date-input" /><button className="dashboard-icon-button" onClick={() => onMonthChange(addMonth(month, 1))} aria-label="Next month"><ChevronRight className="h-4 w-4" /></button></div>;
  return <DashboardSection title={dashboardLabels.monthEnd} icon={Scale} action={action}><SectionState isLoading={isLoading} isError={isError} onRetry={onRetry} emptyText="No month-end data / لا توجد بيانات نهاية الشهر"><>{data && <><div className="mb-4 rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-900"><p>{data.disclosure.en}</p><p dir="rtl" className="mt-1 text-right">{data.disclosure.ar}</p></div><div className="grid grid-cols-1 gap-3 md:grid-cols-3"><MovementPanel title="Customers / الزبائن" movement={data.customers} footer={[['With debt', data.customers.withDebt], ['Fully paid', data.customers.fullyPaid], ['Overdue', data.customers.overdue]]} /><MovementPanel title="Suppliers / المورّدون" movement={data.suppliers} footer={[['With balance', data.suppliers.withBalance]]} /><div className="rounded-lg border border-slate-200 p-3"><h3 className="mb-3 text-sm font-semibold">Service / الصيانة</h3>{[['Opened',data.service.opened],['Completed',data.service.completed],['Pending',data.service.pending],['Cancelled',data.service.cancelled],['Net open',data.service.netOpen],['Avg days open',data.service.averageDaysOpen]].map(([label,value]) => <div key={label} className="flex justify-between border-b border-slate-100 py-1.5 text-xs"><span>{label}</span><strong>{value}</strong></div>)}</div></div><div className="mt-3"><DebtMovementChart data={data.customers} /></div></>}</></SectionState></DashboardSection>;
}

function MovementPanel({ title, movement, footer }: { title: string; movement: MonthEndMovement; footer: Array<[string, number]> }) {
  const rows: Array<[string, string, boolean?]> = [['Opening', movement.opening], ['+ New', movement.newAmount], ['− Collected', movement.collected], ['± Adjusted', movement.adjustments, true], ['= Closing', movement.closing]];
  return <div className="rounded-lg border border-slate-200 p-3"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold">{title}</h3><span className={`inline-flex items-center gap-1 text-[10px] font-semibold ${movement.reconciled ? 'text-green-700' : 'text-red-700'}`}>{movement.reconciled ? <CheckCircle2 className="h-3.5 w-3.5" /> : <TriangleAlert className="h-3.5 w-3.5" />}{movement.reconciled ? 'Balanced' : 'Unreconciled'}</span></div>{rows.map(([label,value,signed], index) => <div key={label} className={`flex justify-between py-1.5 text-xs ${index === 4 ? 'border-t border-slate-300 font-bold' : 'border-b border-slate-100'}`}><span>{label}</span><span>{signed ? formatSignedMoney(value) : formatMoney(value)}</span></div>)}<div className="mt-2">{footer.map(([label,value]) => <div key={label} className="flex justify-between py-1 text-[11px] text-slate-500"><span>{label}</span><strong className="text-slate-700">{value}</strong></div>)}</div></div>;
}

function addMonth(month: string, offset: number) { const date = new Date(`${month}-01T00:00:00Z`); date.setUTCMonth(date.getUTCMonth() + offset); return date.toISOString().slice(0, 7); }

