import { Package } from 'lucide-react';
import { dashboardLabels } from '../../config/dashboard-labels';
import type { ProductAnalyticsData } from '../../types';
import { DashboardSection } from '../layout/DashboardSection';
import { SectionState } from './SectionState';
export function ProductAnalytics({ data, isLoading, isError, onRetry }: { data?: ProductAnalyticsData; isLoading: boolean; isError: boolean; onRetry: () => void }) {
  const totalUsage = Math.max(1, ...(data?.presetUsage.map((row) => row.productCount) ?? [1]));
  return <DashboardSection title={dashboardLabels.productAnalytics} icon={Package}><SectionState isLoading={isLoading} isError={isError} onRetry={onRetry} emptyText="No products / لا توجد منتجات"><div className="grid grid-cols-1 gap-5 lg:grid-cols-2"><div><div className="flex items-end justify-between"><div><span className="text-xs text-slate-500">Catalogue readiness / جاهزية الدليل</span><strong className="mt-1 block text-3xl">{data?.totals.readinessPercent ?? 0}%</strong></div><span className="text-xs text-slate-500">{data?.totals.ready ?? 0} of {data?.totals.active ?? 0} ready</span></div><div className="mt-3 h-3 overflow-hidden rounded bg-slate-100"><div className="h-full bg-emerald-500" style={{ width: `${data?.totals.readinessPercent ?? 0}%` }} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Gap label="Missing barcode" value={data?.totals.missingBarcode ?? 0} /><Gap label="Missing cost" value={data?.totals.missingCost ?? 0} /><Gap label="Missing pricing" value={data?.totals.missingPricing ?? 0} /></div></div><div><h3 className="text-sm font-semibold">Pricing preset usage / استخدام إعدادات التسعير</h3><div className="mt-3 space-y-2">{data?.presetUsage.map((row) => <div key={row.presetId} className="grid grid-cols-[minmax(0,1fr)_3fr_auto] items-center gap-2 text-xs"><span className="user-text truncate" dir="auto">{row.presetName}</span><div className="h-2 rounded bg-slate-100"><div className="h-full rounded bg-amber-500" style={{ width: `${(row.productCount / totalUsage) * 100}%` }} /></div><strong>{row.productCount}</strong></div>)}</div></div></div></SectionState></DashboardSection>;
}
function Gap({ label, value }: { label: string; value: number }) { return <div className="rounded-md bg-slate-50 p-2"><strong className="block text-lg text-slate-900">{value}</strong><span className="text-slate-500">{label}</span></div>; }
