import { Router } from 'express';
import { validate } from '../../../middleware/validate.middleware';
import { requirePricingAdmin } from '../authorization/pricing-policy';
import { PricingPresetsController } from './pricing-presets.controller';
import { LabelSecretConfigController } from '../label-secret/label-secret-config.controller';
import { createLabelSecretEncodingSchema, labelSecretEncodingParamsSchema, updateLabelSecretEncodingSchema, updateLabelSecretSettingsSchema } from '../label-secret/label-secret-config.validator';
import { createPricingPresetSchema, pricingPresetActionSchema, pricingPresetAuditQuerySchema, pricingPresetListQuerySchema, pricingPresetParamsSchema, pricingPresetPasswordActionSchema, updatePricingPresetSchema } from './pricing-presets.validator';

export const pricingPresetsRoutes = Router();
pricingPresetsRoutes.get('/', validate(pricingPresetListQuerySchema, 'query'), PricingPresetsController.list);
pricingPresetsRoutes.post('/', requirePricingAdmin, validate(createPricingPresetSchema), PricingPresetsController.create);
pricingPresetsRoutes.get('/label-secret-settings', LabelSecretConfigController.get);
pricingPresetsRoutes.patch('/label-secret-settings', requirePricingAdmin, validate(updateLabelSecretSettingsSchema), LabelSecretConfigController.updateSettings);
pricingPresetsRoutes.post('/label-secret-encodings', requirePricingAdmin, validate(createLabelSecretEncodingSchema), LabelSecretConfigController.createEncoding);
pricingPresetsRoutes.patch('/label-secret-encodings/:encodingId', requirePricingAdmin, validate(labelSecretEncodingParamsSchema, 'params'), validate(updateLabelSecretEncodingSchema), LabelSecretConfigController.updateEncoding);
pricingPresetsRoutes.get('/:presetId/audit', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(pricingPresetAuditQuerySchema, 'query'), PricingPresetsController.audit);
pricingPresetsRoutes.post('/:presetId/archive', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(pricingPresetActionSchema), PricingPresetsController.archive);
pricingPresetsRoutes.post('/:presetId/restore', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(pricingPresetActionSchema), PricingPresetsController.restore);
pricingPresetsRoutes.post('/:presetId/set-default', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(pricingPresetActionSchema), PricingPresetsController.setDefault);
pricingPresetsRoutes.post('/:presetId/set-label-secret', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(pricingPresetPasswordActionSchema), PricingPresetsController.setLabelSecret);
pricingPresetsRoutes.post('/:presetId/clear-label-secret', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(pricingPresetPasswordActionSchema), PricingPresetsController.clearLabelSecret);
pricingPresetsRoutes.patch('/:presetId', requirePricingAdmin, validate(pricingPresetParamsSchema, 'params'), validate(updatePricingPresetSchema), PricingPresetsController.update);
pricingPresetsRoutes.get('/:presetId', validate(pricingPresetParamsSchema, 'params'), PricingPresetsController.get);
